module.exports = [
  "Aberdeen",
  "Aberdour",
  "Achanalt",
  "Achnasheen",
  "Achnashellach",
  "Addiewell",
  "Airbles",
  "Airdrie",
  "Alexandra Parade",
  "Alexandria",
  "Alloa",
  "Alness",
  "Altnabreac",
  "Anderston",
  "Annan",
  "Anniesland",
  "Arbroath",
  "Ardgay",
  "Ardlui",
  "Ardrossan Harbour",
  "Ardrossan South Beach",
  "Ardrossan Town",
  "Argyle Street",
  "Arisaig",
  "Armadale",
  "Arrochar & Tarbet",
  "Ashfield",
  "Attadale",
  "Auchinleck",
  "Aviemore",
  "Ayr",
  "Baillieston",
  "Balloch",
  "Balmossie",
  "Banavie",
  "Barassie",
  "Bargeddie",
  "Barnhill",
  "Barrhead",
  "Barrhill",
  "Barry Links",
  "Bathgate",
  "Bearsden",
  "Beasdale",
  "Beauly",
  "Bellgrove",
  "Bellshill",
  "Bishopbriggs",
  "Bishopton",
  "Blackridge",
  "Blair Atholl",
  "Blairhill",
  "Blantyre",
  "Bogston",
  "Bowling",
  "Branchton",
  "Breich",
  "Bridge of Allan",
  "Bridge of Orchy",
  "Bridgeton",
  "Brora",
  "Broughty Ferry",
  "Brunstane",
  "Burnside",
  "Burntisland",
  "Busby",
  "Caldercruix",
  "Cambuslang",
  "Camelon",
  "Cardenden",
  "Cardonald",
  "Cardross",
  "Carfin",
  "Carluke",
  "Carmyle",
  "Carnoustie",
  "Carntyne",
  "Carrbridge",
  "Carstairs",
  "Cartsdyke",
  "Cathcart",
  "Charing Cross (Glasgow)",
  "Chatelherault",
  "Clarkston",
  "Cleland",
  "Clydebank",
  "Coatbridge Central",
  "Coatbridge Sunnyside",
  "Coatdyke",
  "Connel Ferry",
  "Conon Bridge",
  "Corkerhill",
  "Corpach",
  "Corrour",
  "Cowdenbeath",
  "Craigendoran",
  "Crianlarich",
  "Croftfoot",
  "Crookston",
  "Crosshill",
  "Crossmyloof",
  "Croy",
  "Culrain",
  "Cumbernauld",
  "Cupar",
  "Curriehill",
  "Dalgety Bay",
  "Dalmally",
  "Dalmarnock",
  "Dalmeny",
  "Dalmuir",
  "Dalreoch",
  "Dalry",
  "Dalwhinnie",
  "Dingwall",
  "Drem",
  "Drumchapel",
  "Drumfrochar",
  "Drumgelloch",
  "Drumry",
  "Duirinish",
  "Duke Street",
  "Dumbarton Central",
  "Dumbarton East",
  "Dumbreck",
  "Dumfries",
  "Dunbar",
  "Dunblane",
  "Duncraig",
  "Dundee",
  "Dunfermline Queen Margaret",
  "Dunfermline Town",
  "Dunkeld & Birnam",
  "Dunlop",
  "Dunrobin Castle",
  "Dyce",
  "East Kilbride",
  "Easterhouse",
  "Edinburgh",
  "Edinburgh Gateway",
  "Edinburgh Park",
  "Elgin",
  "Eskbank",
  "Exhibition Centre (Glasgow)",
  "Fairlie",
  "Falkirk Grahamston",
  "Falkirk High",
  "Falls of Cruachan",
  "Fauldhouse",
  "Fearn",
  "Forres",
  "Forsinard",
  "Fort Matilda",
  "Fort William",
  "Galashiels",
  "Garelochhead",
  "Garrowhill",
  "Garscadden",
  "Gartcosh",
  "Garve",
  "Georgemas Junction",
  "Giffnock",
  "Gilshochill",
  "Girvan",
  "Glasgow Central",
  "Glasgow Queen Street",
  "Gleneagles",
  "Glenfinnan",
  "Glengarnock",
  "Glenrothes with Thornton",
  "Golf Street",
  "Golspie",
  "Gorebridge",
  "Gourock",
  "Greenfaulds",
  "Greenock Central",
  "Greenock West",
  "Gretna Green",
  "Hairmyres",
  "Hamilton Central",
  "Hamilton West",
  "Hartwood",
  "Hawkhead",
  "Haymarket",
  "Helensburgh Central",
  "Helensburgh Upper",
  "Helmsdale",
  "High Street (Glasgow)",
  "Hillfoot",
  "Hillington East",
  "Hillington West",
  "Holytown",
  "Howwood",
  "Huntly",
  "Hyndland",
  "IBM Halt",
  "Insch",
  "Invergordon",
  "Invergowrie",
  "Inverkeithing",
  "Inverkip",
  "Inverness",
  "Invershin",
  "Inverurie",
  "Irvine",
  "Johnstone (Strathclyde)",
  "Jordanhill",
  "Keith",
  "Kelvindale",
  "Kennishead",
  "Kildonan",
  "Kilmarnock",
  "Kilmaurs",
  "Kilpatrick",
  "Kilwinning",
  "Kinbrace",
  "Kinghorn",
  "Kings Park",
  "Kingsknowe",
  "Kingussie",
  "Kirkcaldy",
  "Kirkconnel",
  "Kirkhill",
  "Kirknewton",
  "Kirkwood",
  "Kyle of Lochalsh",
  "Ladybank",
  "Lairg",
  "Lanark",
  "Langbank",
  "Langside",
  "Larbert",
  "Largs",
  "Larkhall",
  "Laurencekirk",
  "Lenzie",
  "Leuchars (for St.Andrews)",
  "Linlithgow",
  "Livingston North",
  "Livingston South",
  "Loch Awe",
  "Loch Eil",
  "Lochailort",
  "Locheilside",
  "Lochgelly",
  "Lochluichart",
  "Lochwinnoch",
  "Lockerbie",
  "Longniddry",
  "Mallaig",
  "Markinch",
  "Maryhill",
  "Maxwell Park",
  "Maybole",
  "Merryton",
  "Milliken Park",
  "Milngavie",
  "Monifieth",
  "Montrose",
  "Morar",
  "Mosspark",
  "Motherwell",
  "Mount Florida",
  "Mount Vernon",
  "Muir of Ord",
  "Muirend",
  "Musselburgh",
  "Nairn",
  "Neilston",
  "New Cumnock",
  "Newcraighall",
  "Newton (Lanark)",
  "Newton-on-Ayr",
  "Newtongrange",
  "Newtonmore",
  "Nitshill",
  "North Berwick",
  "North Queensferry",
  "Oban",
  "Paisley Canal",
  "Paisley Gilmour Street",
  "Paisley St James",
  "Partick",
  "Patterton",
  "Perth",
  "Pitlochry",
  "Plockton",
  "Pollokshaws East",
  "Pollokshaws West",
  "Pollokshields East",
  "Pollokshields West",
  "Polmont",
  "Port Glasgow",
  "Portlethen",
  "Possilpark & Parkhouse",
  "Prestonpans",
  "Prestwick International Airport",
  "Prestwick Town",
  "Priesthill & Darnley",
  "Queens Park (Glasgow)",
  "Rannoch",
  "Renton",
  "Rogart",
  "Rosyth",
  "Roy Bridge",
  "Rutherglen",
  "Saltcoats",
  "Sanquhar",
  "Scotscalder",
  "Scotstounhill",
  "Shawfair",
  "Shawlands",
  "Shettleston",
  "Shieldmuir",
  "Shotts",
  "Singer",
  "Slateford",
  "South Gyle",
  "Spean Bridge",
  "Springburn",
  "Springfield",
  "Stepps",
  "Stevenston",
  "Stewarton",
  "Stirling",
  "Stonehaven",
  "Stow",
  "Stranraer",
  "Strathcarron",
  "Stromeferry",
  "Summerston",
  "Tain",
  "Taynuilt",
  "Thornliebank",
  "Thorntonhall",
  "Thurso",
  "Troon",
  "Tulloch",
  "Tweedbank",
  "Tyndrum Lower",
  "Uddingston",
  "Uphall",
  "Upper Tyndrum",
  "Wallyford",
  "Wemyss Bay",
  "West Calder",
  "West Kilbride",
  "Wester Hailes",
  "Westerton",
  "Whifflet",
  "Whinhill",
  "Whitecraigs",
  "Wick",
  "Williamwood",
  "Wishaw",
  "Woodhall",
  "Yoker"
];
